CREATE DATABASE DB_QLNV CHAR SET UTF8MB4 COLLATE UTF8MB4_BIN;
USE DB_QLNV;

CREATE TABLE USER(
ID INT  AUTO_INCREMENT,
USERNAME VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL,
FULLNAME NVARCHAR(50) NOT NULL,
CONSTRAINT PK_USER PRIMARY KEY (ID)
);

CREATE TABLE DEPART(
ID INT  AUTO_INCREMENT,
CODE CHAR(100) NOT NULL,
NAMEDEPART NVARCHAR(50) NOT NULL,
CONSTRAINT PK_DEPART PRIMARY KEY (ID)
);

CREATE TABLE STAFF(
ID INT  AUTO_INCREMENT,
CODE CHAR(100) NOT NULL,
NAMESTAFF NVARCHAR(50) NOT NULL,
GENDER BIT NOT NULL,
BIRTHDAY VARCHAR(50)  NULL,
PHOTO VARCHAR(100) NULL,
EMAIL VARCHAR(100) NOT NULL,
PHONE VARCHAR(100) NULL,
SALARY FLOAT NOT NULL,
NOTES NVARCHAR(100) NULL,
DEPARTID INT NOT NULL,
CONSTRAINT PK_STAFF PRIMARY KEY (ID),
CONSTRAINT FK_STAFF_DEPART FOREIGN KEY (DEPARTID) REFERENCES DEPART(ID)
);

CREATE TABLE RECORD(
ID INT  AUTO_INCREMENT,
TYPE BIT NOT NULL,
REASON NVARCHAR(100) NOT NULL,
DATE VARCHAR(50) NOT NULL,
STAFFID INT NOT NULL,
CONSTRAINT PK_RECORD PRIMARY KEY (ID),
CONSTRAINT FK_RECORD_STAFF FOREIGN KEY (STAFFID) REFERENCES STAFF(ID)
);

INSERT INTO `DB_QLNV`.`USER` (`USERNAME`,`PASSWORD`,`FULLNAME`) VALUES ('admin','admin','ADMIN');



